repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        args:
          - --safe
          - --line-length
          - "100"
